### ISSUE TITLE
OSC option is not working correctly

### ISSUE THREAD

**Issue by OneB1t** [hudec117/Mpv.NET-lib-#15]
helllo

i have following options for MPV (other are working fine)

            player.API.SetOptionString("vo", "gpu"); // hwdecoder enabled
            player.API.SetOptionString("hwdec", "auto"); // hwdecoder enabled
            player.API.SetOptionString("aid", "no"); // disable audio track
            player.API.SetOptionString("interpolation", "yes");
            player.API.SetOptionString("video-sync", "display-resample");
            player.API.SetOptionString("keepaspect", "no");
            player.API.SetOptionString("osc", "yes");

but for some reason osc is not showing

im able to use this:

player.API.SetOptionString("osd-level", "3");

in order to show atleast some information about running video but osc is not working for me (i also checked for example how they do it inside mpv.net and they have just 
set_property_string("osc", "yes");

i want to see something like this:
![image](https://user-images.githubusercontent.com/320479/64487442-13e21d80-d23b-11e9-85fa-bf63e1906235.png)

thank you

**Comment by hudec117** [comment]
Hello @OneB1t 

Could you please confirm that the "osc" in the image is the "stats" mpv feature?

**Comment by hudec117** [comment]
Hello @OneB1t, there is a similar issue which I've investigated and will likely be the root cause of this as well: https://github.com/hudec117/Mpv.NET.lib/issues/16

**Comment by OneB1t** [comment]
I think that MPV.net must have some workaround so its working for them its not critical for me but it will be nice to see this more complex statistics

**Comment by hudec117** [comment]
From the issue I linked:
> That said, it is possible to forward the events onto mpv from your application. I would refer you to this code written for Mpv.NET (media player), they came across the same problem: https://github.com/stax76/mpv.net/blob/7e8a654ada9c351063cddd3228e04d7fbd2f56db/mpv.net/WinForms/MainForm.cs#L410
From this you can see they overrode the WndProc method and forwarded the appropriate messages to mpv.

So yes, there is a workaround but I have to figure out how it could be implemented since the workaround is dependent on the Window's message queue.

**Comment by OneB1t** [comment]
This is actually not a bug i just not correctly understanded what is required in order to make it work

to load osc statistics it is required to load external script file

so i included something like this to code in order to achieve it

```
		public void EnableOSCStats(string statsScriptPath)
		{
			Guard.AgainstNullOrEmptyOrWhiteSpaceString(statsScriptPath, nameof(statsScriptPath));
			if (!File.Exists(statsScriptPath))
				throw new FileNotFoundException("Cannot find stats script.");
			lock (mpvLock)
			{
				mpv.Command("load-script", statsScriptPath);
				mpv.Command("script-binding","stats/display-page-1");
			}
		}
```

Thanks for help :)

**Comment by OneB1t** [comment]
Ok actually looks like 
mpv.Command("script-binding","stats/display-page-1");

is enough to show OSD data but only for 4seconds as there is duration inside lua script... so next issue is to show it forever
