### ISSUE TITLE
How can I use config file with MpvPlayer

### ISSUE THREAD

**Issue by Fantoom** [hudec117/Mpv.NET-lib-#17]

**Comment by Fantoom** [comment]
I have added 
```
        public void LoadConfig(string absolutePath) 
	{
		mpv.LoadConfigFile(absolutePath);
	}
```

to Mpv.NET.Player.MpvPlayer and it worked.

**Comment by hudec117** [comment]
Hello @Fantoom,

I will include this feature in the next release of Mpv.NET. In the meantime, a workaround that does not require re-compilation of the latest release is:
```csharp
player.API.LoadConfigFile("my/absolute/path/to/config");
```
The "API" property on the player is a reference to an instance of the "Mpv" class that is being used by the player.
