### ISSUE TITLE
A problem about mpv.net

### ISSUE THREAD

**Issue by GongKuiJun** [hudec117/Mpv.NET-lib-#19]
**Mpv.NET (lib) Version**
1.1.1
**Describe the bug**
I can't change "- no keepsaspect, -- keepsaspect"

I want to know how I need to modify it

**Comment by hudec117** [comment]
Please provide steps to reproduce the error and the actual and expected results.

**Comment by hudec117** [comment]
No response to help reproduce issue. Closing issue
