### ISSUE TITLE
Difference between Mpv.net- lib and Mvp.Net

### ISSUE THREAD

**Issue by ericleroy01** [hudec117/Mpv.NET-lib-#35]
Hi,

what difference between your project and https://github.com/stax76/mpv.net ?

what are advantages to use you library ?

(my goal is to use mpv player on xbox platform)
thanks.

PS: Si quelqu'un pouvait echanger avec moi en francais ca serait plus facile :)

**Comment by hudec117** [comment]
The project you linked is a fully featured Windows media player that uses mpv and is built using .NET

This project is a library that you can use to add a video player to a WPF or Windows Forms application.

**Comment by ericleroy01** [comment]
I understood this project is a library...

I don t give a look to mpv.net source code but player seems to implement all base mpv functionalities and you mentionned is not your case.... so what is your roadmap ?

**Comment by hudec117** [comment]
Mpv.NET is specifically designed and created to be a Windows media player. It may implement the same mpv functionalities but the application is meant to be used by people to play media, it's not aimed specifically at developers to develop new applications.

While this library is merely an interface to the C API exposed by the mpv library that is consumable from .NET and is meant to be used by developers to play media in their custom applications.

I'm not planning on developing new features but I will look to maintain the code and I'm happy to accept new features from others.

**Comment by ericleroy01** [comment]
I attempt to included libmpv in my project based on your work and mpv.net.

My main issue is Window or control handle which does not exist in UWP project.
I tried to use renderGL api but it s required a window/or control handle too.

thanks for your help
