### ISSUE TITLE
How to set aspect ratio, snapshot, get video info ?

### ISSUE THREAD

**Issue by pubpy2015** [hudec117/Mpv.NET-lib-#39]
Hi,

can you add some function as set aspect ratio mode (16:9, fit to screen,...), snapshot current video frame and get some information from video as: Resolution, Frame Rate, BitRate ?

**Comment by songoku141** [comment]
I found function to set aspect ratio: 
player.API.SetPropertyString("video-aspect", panel1.Width + ":" + panel1.Height);

snapshot to file: 
player.API.Command("screenshot-to-file", "C:\\1.jpg");

I trying to get snapshot and save it in buffer by this command:
player.API.Command("screenshot");
but I dont know where is data return. 
Please help me.

**Comment by zpmmehrdad** [comment]
@songoku141 Hi,

How can I set the jpeg quality parameter? I used this command 
`player.API.Command("screenshot-to-file", "C:\1.jpg", "screenshot-jpeg-quality", "70");`
but I got the invalid parameter error.

Thanks

**Comment by songoku141** [comment]
You can try like this:
player.API.SetPropertyLong("screenshot-jpeg-quality", 70);
player.API.Command("screenshot-to-file", "C:\\1.jpg");

**Comment by pubpy2015** [comment]
Thanks,

seem don't have command for screenshot to memory:
https://mpv.io/manual/master/#screenshot
close here.

**Comment by zpmmehrdad** [comment]
> You can try like this:
> player.API.SetPropertyLong("screenshot-jpeg-quality", 70);
> player.API.Command("screenshot-to-file", "C:\1.jpg");

@songoku141 Hi,

Thanks for the reply, But when I use this command I get an error:
```
 player.API.SetPropertyLong("screenshot-webp-quality", 75);
 player.API.Command("screenshot-to-file", $@"d:\{rnd}.webp");
```

Parameter not found

**Comment by zpmmehrdad** [comment]
> Thanks,
> 
> seem don't have command for screenshot to memory:
> https://mpv.io/manual/master/#screenshot
> close here.

Hi,

Did you try this command?

["screenshot-raw"](https://github.com/mpv-player/mpv/blob/6b828113a89b39888cde6ff89b1ae0f39a0cb4ee/DOCS/man/input.rst)
player.API.Command("screenshot-raw");

But I don't know, How to get the output in memory.
