### ISSUE TITLE
Select GPU device

### ISSUE THREAD

**Issue by sctrueew** [hudec117/Mpv.NET-lib-#40]
Hi,

I have two GPUs,

GPU 0: Intel(R)
GPU 1: NVIDIA GeForce GTX 1650

mpv is using GPU 0 but I would like to use GPU 1. How can I set it?

Thanks

**Comment by mysteryx93** [comment]
Normally you use NVIDIA control panel to control what GPU each application uses. Add your app and tell it to use "performance" GPU.

**Comment by hudec117** [comment]
@mysteryx93 is on the right lines. I found this after a quick Google: https://www.reddit.com/r/mpv/comments/dm9vxy/comment/f512goh/?utm_source=share&utm_medium=web2x&context=3

Try adding your app's executable to NVIDIA control panel and selecting the GPU.
