### ISSUE TITLE
How to not open a new Mpv window when playing audio with cover art

### ISSUE THREAD

**Issue by ywmoyue** [hudec117/Mpv.NET-lib-#47]
**Mpv.NET (lib) Version**
1.2.0

**Describe the bug**
A new Mpv window will automatically open when playing audio with cover art

**To Reproduce**
```cs
var player = new MpvPlayer(MpvLibPath);
player.Load(url); //url: A url to the audio with the cover
player.MediaLoaded += (object sender,EventArgs e)=>{ player.Resume(); };
```

**Expected behavior**
Don't open a new window while playing audio

**Screenshots**
![image](https://user-images.githubusercontent.com/28388300/144695784-882340fe-5113-4e69-b40f-ebceb0b31e9a.png)

**Comment by hudec117** [comment]
Hello @ywmoyue. Try setting this property:

![image](https://user-images.githubusercontent.com/10981949/146674956-4524e585-9187-4a58-ac8a-fd8de94c951e.png)
https://mpv.io/manual/master/#options-audio-display
